### ISSUE TITLE
support of bootstrap based themes

### ISSUE THREAD

**Issue by AndreScherl** [mebis-lp/moodle-qtype_geogebra#1]
Hello, 

there are problems on displaying the ggb-applet container within question settinigs and question view, if your moodle runs with an bootstrap based theme.
The heigth or more generally the size of the applet container is not calculated and set correctly.
Here's one exaple screenshot:
![qtype_geogebra_issue](https://cloud.githubusercontent.com/assets/1030171/10068272/572fcb66-62a3-11e5-94a5-df90914129ce.jpg)

Best regards,
Andre

**Comment by nadavkav** [comment]
+1 for getting this fixed
