### ISSUE TITLE
Ability to download the the GGB file

### ISSUE THREAD

**Issue by nadavkav** [mebis-lp/moodle-qtype_geogebra#11]
After using the ggb file in the question for some time, I would like to download it, modify it and upload it again, but I am unable to download the original ggb file.

It could be very helpful if I could editor it online :-)
To save me from downloading it, modifying it and uploading it again.

Please advise

**Comment by nadavkav** [comment]
@murkle Can you evaluate the cost for developing this feature? so I can see if I have a budget for it.

**Comment by murkle** [comment]
@nadavkav Please email office@geogebra.org
