### ISSUE TITLE
Problems with display and correction

### ISSUE THREAD

**Issue by jlmunoz161** [mebis-lp/moodle-qtype_geogebra#13]
Hi!!

I am trying to use the plugin but I have three problems:

1. I can't see the text of the question.(I think it could be fixed by modifying line 93 of renderer.php)
2. The applet always comes out of place.
3. Does not correct well

I have moodle 3.7.2+ Build 2090927 and 
<img width="812" alt="Captura de pantalla 2020-05-24 a las 17 13 29" src="https://user-images.githubusercontent.com/65860967/82757628-f9a89980-9de1-11ea-9df4-01b7c6b90ca9.png">
php 7.3.16.1

Thank you!!

**Comment by PM84** [comment]
Unfortunately, the plugin is no longer maintained by Geogebra. Therefore the mebis-Bayern team has decided to continue maintaining this plugin. We have made the plugin fit for Moodle 3.11.

We have already fixed items 1 and 2 on your list.

If you find another bug or just want to contribute, we are looking forward to your contribution.

You can find the plugin at: https://github.com/mebis-lp/moodle-qtype_geogebra

**Comment by PM84** [comment]
Number 2 is fixed with aa7421aac27c402fcf7d3863bda623c988757e8b

What do you mean with "Does not correct well". Can you please elaborate a bit?
Actually, you should check whether a result is correct or not in your ggb worksheet and not in moodle.

**Comment by jlmunoz161** [comment]
I seem to remember that the reason it didn't work well was because I didn't check the solution properly.

In the next few days I will test the new development and comment on it.

Thanks for your work

**Comment by PM84** [comment]
#24
