### ISSUE TITLE
Moodle 3.8 Support

### ISSUE THREAD

**Issue by superfoght** [mebis-lp/moodle-qtype_geogebra#16]
After upgrading a site to Moodle 3.8, I am experiencing an error where there is a solid white div that is placed over the Geogebra applet, so it's not visible.

The class of the div is .ggb_preview

I have tested a similar question in Moodle 3.6 and it works there.

**Comment by elektrosmart** [comment]
Did you get this solved?

**Comment by superfoght** [comment]
Not really. I made a dirty fix with CSS in the Moodle Theme. But I guess it's still an issue if you don't have access to fixing it through CSS.

**Comment by PM84** [comment]
Unfortunately, the plugin is no longer maintained by Geogebra. Therefore the mebis-Bayern team has decided to continue maintaining this plugin. We have made the plugin fit for Moodle 3.11.

If you find another bug or just want to contribute, we are looking forward to your contribution.

You can find the plugin at: https://github.com/mebis-lp/moodle-qtype_geogebra

**Comment by PM84** [comment]
The version for Moodle 3.11 should also run under Moodle 3.8. (untested)
