### ISSUE TITLE
Version 1.9.2 in moodle 3.9.2+; only two changes necessary

### ISSUE THREAD

**Issue by mputzi** [mebis-lp/moodle-qtype_geogebra#17]
Today I examined the problem again and found that only two CSS-properties would have to be changed. Then the question-type would be working well in even with the recent version of moodle.

1. The question text (CSS-class qtext) is generated with style="visibility: hidden;". Removing this CSS-style gives a correct display of the question text.
![Screenshot_20200930_102828](https://user-images.githubusercontent.com/5164032/94661993-10b74500-0308-11eb-8631-c601a1670c09.png)

2. Height an width of the ggb-applet are calculated too late or the rendering needs to be refreshed. So at first load one gets stuck with an applet overflowing the question-div. 
![Screenshot_20200930_103805](https://user-images.githubusercontent.com/5164032/94662714-106b7980-0309-11eb-9a3b-52cd390ec08d.png)

**Comment by mputzi** [comment]
I made these changes in #18  and #19 .
Please accept my pull requests.

**Comment by nadavkav** [comment]
Thank you @mputzi for fixing this :smile:

**Comment by PM84** [comment]
Accepted: https://github.com/mebis-lp/moodle-qtype_geogebra/commit/e0d29c667ed6bb1f6f3fd4041546346854772f2b
