### ISSUE TITLE
 Moodle 3.9 version?

### ISSUE THREAD

**Issue by Urpokarhu1** [mebis-lp/moodle-qtype_geogebra#21]
Hello,

When is Moodle 3.9 version going to be released?

**Comment by PM84** [comment]
Unfortunately, the plugin is no longer maintained by Geogebra. Therefore the mebis-Bayern team has decided to continue maintaining this plugin. We have made the plugin fit for Moodle 3.11.

If you find another bug or just want to contribute, we are looking forward to your contribution.

You can find the plugin at: https://github.com/mebis-lp/moodle-qtype_geogebra

**Comment by PM84** [comment]
The version for Moodle 3.11 should also run under Moodle 3.9. (untested)
