### ISSUE TITLE
URL linked ggb

### ISSUE THREAD

**Issue by TWINGSISTER** [mebis-lp/moodle-qtype_geogebra#22]
I cannot see a ggb working when I use to link it by a URL that is a shared link from Nextcloud.
Probably URL means a URL pointing the Geogebra site. Can you please give me some enlightenment about that?

**Comment by PM84** [comment]
Yes, the URL has to point e.g. to geogebra materials. 
 
Unfortunately, the plugin is no longer maintained by Geogebra. Therefore the mebis-Bayern team has decided to continue maintaining this plugin. We have made the plugin fit for Moodle 3.11.

If you find another bug or just want to contribute, we are looking forward to your contribution.

You can find the plugin at: https://github.com/mebis-lp/moodle-qtype_geogebra
