### ISSUE TITLE
Problems (every versions, every time in my case)

### ISSUE THREAD

**Issue by Bejagui** [mebis-lp/moodle-qtype_geogebra#25]
Hello everybody.

First of all I want to thank everyone who has contributed to the development and administration of this plugin. Users (teachers) usually ask for application updates or report problems but this time I want to highlight how important and useful this plugin has been for me. Thanks.

I recently participated in an answer but perhaps it makes more sense to place it as a separate topic.

I have worked with this plugin because although it has some limitations, it is wonderful that students carry out their activities and exams with the practices that GeoGebra allows. However, from the beginning I have dealt with various problems.

Problem 1: It has not been easy for me to find documentation for this plugin: tips, requirements, way of interacting between GeoGebra and Moodle (I know that it is very easy to "ask for" and "ask for" and "ask for" things without giving anything in return; but if possible, create a simple and complete manual. I think it would help a lot but me.

Problem 2: The random variables of GeoGebra do not correspond to the variables that Moodle takes. I have solved this problem by placing the instructions within Geogebra; but the text gets in the way of the activity.

Problem 3: When the student wants to review his exercise, the initial conditions of the exercise change due to the random variables. So he can't know where he went wrong (neither can I, by the way, so I can't explain it to him). I have solved this problem by canceling the random option in both GeoGebra and Moodle; and I have to do 20 different exercises in GeoGebra and 20 questions in Moodle. It's silly, but I couldn't do it any other way.

Again, thank you very much for your work and the time you put into this.

**Comment by PM84** [comment]
Thank you for the suggestions.

I see point 1 the same way. That's why we started a wiki to document the functions more and more: 
https://github.com/mebis-lp/moodle-qtype_geogebra/wiki

Point 2: is in work 

Point 3: this is a topic for the future roadmap. I agree with you though. It's not ideal at the moment.

**Comment by Bejagui** [comment]
Perfect. Thanks.
