### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by dbauer-ets** [mebis-lp/moodle-qtype_geogebra#26]
Hello,

I have reproduced the question presented in Tom Killoran's video available at https://www.youtube.com/watch?v=ZHIf2rDESaM.

The applet is available at https://www.geogebra.org/m/rbvf4qzh.

The Geogebra question is available at https://moodleformulas.org/course/view.php?id=35&section=26.

Although the Geogebra question is working properly, I could not resolve the following issues:

1. On a new attempt, the equation is updated only when moving the mouse over the graph area then off the graph area.
2. The answer feedbacks for the variables are not displayed.

**Comment by PM84** [comment]
I close this issue, because tha latest release 1.11.2 fixes at least one of the issues. If there are any further problems, please do not hesitate to open another issue. I will then try to fix the problem as soon as possible.
