### ISSUE TITLE
Resizing does not work with uploaded  ggb files

### ISSUE THREAD

**Issue by PM84** [mebis-lp/moodle-qtype_geogebra#32]
Hi ... 
may be the same problem.

I have a file like this one https://www.geogebra.org/m/q9qn2G5h

When I do upload it to the question ... the size is like you can see it on the materials page
![Screenshot_20211206_091734](https://user-images.githubusercontent.com/13196996/144811313-bbb3a068-6051-4d1c-84df-59d2e01ee0b6.png)

If I link to the materials-page, the size is bigger. It uses the full size of the page:

... below you can
![Screenshot_20211206_091904](https://user-images.githubusercontent.com/13196996/144811648-2e90df31-cf7c-4914-a60a-5d2553cdc9d6.png)
 see the other question with download

Making the browser windows smaler -> it does not always fits the GeoGebra-Window to the "blue area".
![Screenshot_20211206_092119](https://user-images.githubusercontent.com/13196996/144812152-68e43357-3896-4f8b-b90f-b387918001ff.png)

![Screenshot_20211206_092242](https://user-images.githubusercontent.com/13196996/144812182-eeae73bb-666d-4bf6-b14e-0cb628c4e465.png)

moodle-Version ist 3.9.x

Best wishes and thanks from RLP ...
Birgit Lachner

_Originally posted by @BiLachner in https://github.com/mebis-lp/moodle-qtype_geogebra/issues/23#issuecomment-986543662_

**Comment by PM84** [comment]
4712ae50470792c3bfaafa79c618bdf4d73ab11c should solve the problem until the final redesign of the plugin we are working on

**Comment by schema60** [comment]
ich habe das selbe Problem wie Birgit Lackner - die hochgeladen ggbs in den Moodlefragen werden zu groß und manchmal auch zu klein angezeigt, die eingestellte Größe von 900 *500 wird ignoriert - nun habe ich diesen Post gefunden und 4712ae5 heruntergeladen, aber moodle sagt, es gibt eine neuere Version des Plugins vom 310122.  Ich habe ca 100 geogebraübungen auf www.mathe4alle.at, die nicht mehr gut gelöst werden können (bei manchen ist der StartButton nicht sichtbar (zu kleine Ansicht), andere können nicht abgeschlossen werden, weil etwas zugedeckt wird. Gibt es ein neueres Plugin oder irgendeine Idee. 
![image](https://user-images.githubusercontent.com/102393613/160216025-1db76116-aef3-4fe8-9de3-09f0d3a266eb.png)
Beim zweiten Bild sieht man den Startbutton nicht 
![image](https://user-images.githubusercontent.com/102393613/160216173-325ef3f3-7cbc-4036-9945-5cee7e3ef3cc.png)
