### ISSUE TITLE
Feedback in boolean variables not retrievd automatically in GeoGebra question type plugin in moodle

### ISSUE THREAD

**Issue by uliberlin** [mebis-lp/moodle-qtype_geogebra#36]
Hi again,
this may be a minor issue or even a feature - but I have to collect the text captions for feedback manually each time I edit the question; see 2 screenshots.
Moodle version: 3.9
Plugin 2021100500 Release 1.11.2

Thanks for any help,
Ul
![boolean variables text not sought automatically](https://user-images.githubusercontent.com/96977702/148921684-b7e2ac56-0d4e-46b9-8340-63a5b4fbd43d.jpg)
![boolean variables text manually](https://user-images.githubusercontent.com/96977702/148921695-97e73d78-8a9e-4757-ad0f-715348b01926.jpg)
i

**Comment by mputzi** [comment]
- The boolean variables for the Answers and automatic grading are also not (anymore) automatically retrieved from the ggb file / material link.
- The description fields of the boolean variables are also not (anymore) loaded as specific feedback.

**Comment by PhMemmel** [comment]
@uliberlin The linked PR will solve that.
