### ISSUE TITLE
Größe der Geogebra-Dateien passt nicht 

### ISSUE THREAD

**Issue by schema60** [mebis-lp/moodle-qtype_geogebra#39]
Liebe Community, habe leider in einen geschlossenen Thread geschrieben. Hier nun nochmal: 
Ich habe das selbe Problem wie Birgit Lackner - die hochgeladen ggbs in den Moodlefragen werden zu groß und manchmal auch zu klein angezeigt, die eingestellte Größe von 900 *500 wird ignoriert - nun habe ich diesen Post gefunden und https://github.com/mebis-lp/moodle-qtype_geogebra/commit/4712ae50470792c3bfaafa79c618bdf4d73ab11c heruntergeladen, aber moodle sagt, es gibt eine neuere Version des Plugins vom 310122. Ich habe ca 100 Geogebraübungen auf [www.mathe4alle.at](http://www.mathe4alle.at/), die nicht mehr gut gelöst werden können (bei manchen ist der StartButton nicht sichtbar (zu kleine Ansicht), andere können nicht abgeschlossen werden, weil etwas zugedeckt wird. 
Gibt es ein neueres Plugin oder irgendeine Idee? Oder welche Datei im GeogebraOrdner-in Questions-Types kann ich aktualisieren? 
![image](https://user-images.githubusercontent.com/102393613/160216025-1db76116-aef3-4fe8-9de3-09f0d3a266eb.png)
Beim zweiten Bild sieht man den Startbutton nicht 
![image](https://user-images.githubusercontent.com/102393613/160216173-325ef3f3-7cbc-4036-9945-5cee7e3ef3cc.png)
Ich wäre sehr dankbar für eine Lösung  Marlis Schedler

**Comment by PhMemmel** [comment]
Hallo Marlis, kannst du mal die exakte Fehlermeldung posten? Nutzt du evtl. den Fork von @mputzi ? Falls ja und die Version, über die moodle sich beschwert, wäre "2022013001" (das wäre übrigens Unterversion 1 vom 30.01.2022), nutzt du bereits eine Version, die diesen Fix enthält.

Wenn das Problem trotzdem noch auftaucht, scheint das noch nicht vollständig behoben zu sein. Dann wäre es hilfreich, wenn du hier eine solche fehlerhafte geogebra-Datei/-Aufgabe hochladen könntest.

**Comment by schema60** [comment]
Vielleicht hilft noch folgender Hinweis: Auch früher war das Fenster mal zu klein - aber dann konnte man das Geogebrafenster mit Strg und dem Mausrad vergrößern, verkleinern. Eigentlich ist das der große Unterschied, wenn ich das jetzt mache, dann wird beim oberen Bild der blaue Bereich größer, aber nicht der Geogebra-Inhalt. Beim unteren Bild wird die weiße Fläche rundherum größer und damit der Geogebra-Inhalt zu klein. 
Lösung - Fenster anpassen, dann noch mal aktualisieren - wenn es nur meine Klasse betreffen würde, würde ich es ihnen einfach zeigen - ich habe aber eine öffentliche Plattform für lernschwache Kinder - die lesen natürlich die Hinweise nicht ... und steigen aus, weil sie nicht weiterkommen. Viellicht hilft der Hinweis ja noch. Liebe Grüße Marlis

**Comment by PhMemmel** [comment]
Also ich habe mir das Problem einmal angesehen und hätte auch den ein oder anderen Lösungsansatz, wie man das angehen könnte, kann aber Stand jetzt noch nichts versprechen.

Nur zur Klarstellung: @schema60 Du sagtest, du hast irgendwo 900x500 eingestellt? Wo genau war das? Im Plugin selbst gibt es keine Möglichkeit, eine Größe einzustellen?

**Comment by schema60** [comment]
Lieber PhMemmel, wenn man die ggb Datei auf geogebra hochladet und dort auf erweiterte Einstellungen klickt, kann man einen Wert eingeben - da haben wir immer 900*500px, dann erhält man das Applet, welches in die Frage bei Moodle eingebaut wird. 
Ich habe inzwischen mit einen Kollegen, der sich sehr gut auskennt - über css Anpassungen (max Breite und Höhe) in einigen Feldern eine Zwischenlösung gefunden, damit nichts mehr zugedeckt wird. Dies ist aber nur für uns eine Lösung, weil unsere Applets immer diese fixe Größe haben. Hilft es, wenn du weißt, welche Felder ich anpassen musste? Liebe Grüße Marlis 
![screen_900_500](https://user-images.githubusercontent.com/102393613/161039117-885d65fd-21a9-4351-9d14-011d4e5bd885.png)
![screen_css](https://user-images.githubusercontent.com/102393613/161039120-759a1a0d-985c-49ff-9de5-7752627593f6.png)
