### ISSUE TITLE
Copying Geogebra Question Type Looses Multiple Tries

### ISSUE THREAD

**Issue by killoran** [mebis-lp/moodle-qtype_geogebra#4]
When copying a Geogebra question type from one class to another using the Question Export/Import I found that they Multiple Tries kept the Percent, but lost the words, thus there would be no multiple attempts for the students.

**Comment by cmiicbrg** [comment]
Thanks for reporting, I will look into it.

**Comment by PM84** [comment]
Does the problem still exist?
