### ISSUE TITLE
Some ggbtrans problems in traditional Chinese

### ISSUE THREAD

**Issue by nuhero** [mebis-lp/moodle-qtype_geogebra#46]
Hi, I'm Edward, one translator for traditional Chinese.
I found that some translation have been replaced by simplified Chinese after Dec. 14 ggbtrans update. Try to modify but fail to save.
[image.png](https://drive.google.com/file/d/1Z1eI_RN5dX-6xmRu3PlOOfWgthnirNrM/view?usp=sharing)

Is it possible to reverse back to the original traditional Chinese version?
Or just fix the saving problem then I will modify by myself.

Thanks a lot,

Edward

**Comment by PhMemmel** [comment]
Hi @nuhero, I am pretty sure this is not the right place for your question, sorry.

This is the issue tracker of the moodle question type for geogebra. You may want to contact the folks from the GeoGebra main project.
