### ISSUE TITLE
Move localization to AMOS

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/moodle-qtype_geogebra#49]
All the files `lang/*/qtype_geogebra.php` except from `lang/en/qtype_geogebra.php` should be removed from the repository and uploaded to AMOS.

Unfortunately there is no bulk option for that, so we need to upload every single file. Sometimes the files also contain English lang keys. They should be excluded. After this being done the localization community can take care of the translations.

**Comment by tholudwig** [comment]
- [ ] af
- [ ] ar
- [ ] ar-MA
- [ ] ar-TN
- [ ] bg
- [ ] bs
- [ ] ca
- [ ] ca-XV
- [ ] cs
- [ ] cy
- [ ] da
- [ ] de
- [ ] de-AT
- [ ] el
- [ ] en
- [ ] en-AU
- [ ] en-GB
- [ ] eo
- [ ] es
- [ ] es-ES
- [ ] es-uY
- [ ] et
- [ ] eu
- [ ] fa
- [ ] fi
- [ ] fil
- [ ] fr
- [ ] ga
- [ ] gl
- [ ] he
- [ ] hi
- [ ] hr
- [ ] hu
- [ ] hu-gm
- [ ] hy
- [ ] id
- [ ] is
- [ ] it
- [ ] ja
- [ ] ji
- [ ] ka
- [ ] kk
- [ ] km
- [ ] kn
- [ ] ko
- [ ] lt
- [ ] lv
- [ ] mk
- [ ] ml
- [ ] mn-mn
- [ ] mr
- [ ] mr
- [ ] nb
- [ ] ne
- [ ] nl
- [ ] nl-BE
- [ ] nn
- [ ] no
- [ ] pl
- [ ] pt
- [ ] ot-PT
- [ ] ro
- [ ] ru
- [ ] si
- [ ] sk
- [ ] sl
- [ ] sq
- [ ] sr
- [ ] sv
- [ ] ta
- [ ] tg
- [ ] th
- [ ] tr
- [ ] ty
- [ ] ug
- [ ] uk
- [ ] ur
- [ ] vi
- [ ] xh
- [ ] zh
- [ ] zh-CN
- [ ] zh-TW

**Comment by PhMemmel** [comment]
Done, lang files in this repo removed by #50
