### ISSUE TITLE
Comment from GeoGebra-Boolean-Variable ist not used in Feedback

### ISSUE THREAD

**Issue by BiLachner** [mebis-lp/moodle-qtype_geogebra#51]
Hi ... 
thanks für the last changes: scaling work perfectly and Error when checking wether right or wrong works too!

But ... the Feedback that is saved as "label" of the boolean Variable to tell moodle that it is wrong or false is not used in the report after the test:
![Screenshot_20220516_095038](https://user-images.githubusercontent.com/13196996/168547372-b4e461ba-0f41-4428-9d1e-abff47584b38.png)
![2022-05-16_09-56](https://user-images.githubusercontent.com/13196996/168547475-260df40c-79f3-4f25-9936-22099852b722.png)

Here the settings of the question:
![Screenshot 2022-05-16 at 10-01-36 Bearbeiten einer GeoGebra-Frage](https://user-images.githubusercontent.com/13196996/168547552-3fcaf9ed-c28c-4251-87ac-14a267ae7ad5.png)

Here the file I used: https://www.geogebra.org/m/mpcwwb2q

Birgit

**Comment by PhMemmel** [comment]
Hi Birgit,

after some testing I can state that this feature is not completely broken, because it works for me with my geogebra test files. However, there seem to be some conditions causing an error while parsing the GeoGebra variables in the current implementation. Fix incoming...
