### ISSUE TITLE
Dropping File Gets Resised

### ISSUE THREAD

**Issue by killoran** [mebis-lp/moodle-qtype_geogebra#6]
Moodle 3.4.3
I am dropping a trig graph which has greater width to length (2:1)  and it is resized square.  It makes the graph small and difficult to read so that students can find.  Last year I dropped different sized graphs and they stayed whatever my window size I had.  
<img width="1099" alt="screen shot 2018-06-27 at 12 38 03 pm" src="https://user-images.githubusercontent.com/29458178/41987448-29481928-7a07-11e8-919f-bce7481e6da5.png">
<img width="897" alt="screen shot 2018-06-27 at 12 38 59 pm" src="https://user-images.githubusercontent.com/29458178/41987457-2fc65738-7a07-11e8-9eb9-b8ac33e722e3.png">

Is there something that can be done to adjust this?

By the way, I made a few videos in YouTube to promote this Question Type.  Here are the links:
https://youtu.be/8aMZGoyAeDU
https://youtu.be/ZHIf2rDESaM
https://youtu.be/7Ol7J5M7IIs

**Comment by PM84** [comment]
![Menu_270](https://user-images.githubusercontent.com/7900120/123255075-b55d6080-d4ef-11eb-8f57-d90f1f37f22c.png)
You can work around square zooming by fixing the aspect ratio in your worksheet.
