### ISSUE TITLE
Comments of Solving-Variables are not used within moodle

### ISSUE THREAD

**Issue by BiLachner** [mebis-lp/moodle-qtype_geogebra#66]
Okay, the questions-Types now works, more or less.
- size -> checked!
- get result from Boolean-Variables-> checked! (old questions have problems, but I don't know why!?!?!)

But the caption/label of the Boolean-Variables are not used within moodle. And no preview in the question editing view.
![Screenshot_20220712_060511](https://user-images.githubusercontent.com/13196996/178406408-4bfdd049-a88b-4ebc-96d2-63e675dd23aa.png)
![Screenshot_20220712_060557](https://user-images.githubusercontent.com/13196996/178406419-692cf6cf-f03e-4dfb-80ba-77134117985e.png)

I wonder if it is necessary to read out the caption/label from GeoGebra? This would only have a real advantage if the comments were generated dynamically, which is possible (https://wiki.geogebra.org/en/Labels_and_Captions).
I cannot currently test whether something then arrives in moodle.

But an easy solution for the problem is, to ignore the caption/label and let the teacher enter the comment to a specific true variable.

Birgit

**Comment by PhMemmel** [comment]
Hi Birgit,

this is already fixed, but not included in the latest release on moodle.org. I just tried the question you posted again (it is https://www.geogebra.org/m/mpcwwb2q, right?) and it works for me:

![grafik](https://user-images.githubusercontent.com/65113153/178418227-925e6031-f8e6-4905-9a65-938225d90de3.png)

This is in moodle 3.11.7 with the latest qtype_geogebra plugin version (master branch).

And thank you for the suggestion: It might be a good idea to provide a way to enter the feedback manually. While reworking this plugin we also want to use the generated labels, but being able to overwrite it from the qtype settings would be a nice feature, yes. We will have to find a way to not screw up the usability though :-)

**Comment by BiLachner** [comment]
Okay, yes that's this GGB-File. 
The boolean-variables that are needed are "moodeAufgabeKontrolleRichtig" and "moodeAufgabeKontrolleFalsch".

Looks good, thanks!

Birgit

**Comment by PhMemmel** [comment]
Thanks for confirming. I raised #67 to keep track of your suggestion and closing this as fixed.
