### ISSUE TITLE
Text in Graph File is lost

### ISSUE THREAD

**Issue by killoran** [mebis-lp/moodle-qtype_geogebra#7]
This is new starting on 09/29/2018.  My geogebra questions have lost the question text on the graph part.  
![screen shot 2018-09-29 at 11 46 23 am](https://user-images.githubusercontent.com/29458178/46247713-6c7b2a80-c3dd-11e8-8380-6fa7574d40af.jpg)
![screen shot 2018-09-29 at 11 47 02 am](https://user-images.githubusercontent.com/29458178/46247716-700eb180-c3dd-11e8-8f99-bc9c7caa9363.jpg)

**Comment by PM84** [comment]
Does the problem still exist?
