### ISSUE TITLE
Import forgets some properties.

### ISSUE THREAD

**Issue by TWINGSISTER** [mebis-lp/moodle-qtype_geogebra#77]
When importing a Quiz containing a GGB qtype I found that "Force applet dimensions" is not copied while others (e.g. "Show Toolbar") get copied. Not sure where to look for to fix this. Cheers

**Comment by TWINGSISTER** [comment]
Thanks for your prompt reply. Actually I was talking about Imports, not restore. I do not know if the same problem arise in backups. Could be that the two things are coupled in the implementation but I do not know. If you need I can try if this happens in backups, too. However looking in backup_qtype_geogebra_plugin.class.php the 'forcedimensions' for instance is  actually missing so it is likely they do not get recorded in the backup. Adding them and importing a question where  'forcedimensions'  is set makes it propagate. I will add this in backup_qtype_geogebra_plugin.class.php but, possibly, it is not that easy to fix this issue. Pls comment. I need to propagate also all the options I have introduced in my fork. Look forward to discsuss the related pull request
Cheers

**Comment by PhMemmel** [comment]
Hi @TWINGSISTER, I just tested that it should be sufficient to add the missing properties into the backup controller class. Duplicating as well as importing is basically done the same way in moodle by backuping and restoring internally. So fixing the backup routine to also include the new fields should fix it altogether.

**Comment by TWINGSISTER** [comment]
Great job! pls consider to give a try to other mods in the pull request. Cheers

**Comment by PhMemmel** [comment]
As I stated in #72 we currently are about to refactor the plugin more or less completely, so we cannot accept any kinds of contributions until this will be done. After that (this for sure will take some months unfortunately), we can consider your contributions. Thank you very much in advance!

**Comment by TWINGSISTER** [comment]
Unfortunately I need to use this in class that means "now" so I  need to  keep my fork alive.  It would be nice to have a unique plugin so that I can delete my fork that could be misleading.  Look forward to hear from you soon.
